static-web:

  image: nginx
  environment:
  - VIRTUAL_HOST=test.localhost

  volumes:
  - ./src:/usr/share/nginx/html:ro
  expose:
  - 80
  restart: unless-stopped
# uncomment if you don't have another proxy
#  port:
#  - 80:80
